### ISSUE TITLE
Use `usePocketbase` on server API route

### ISSUE THREAD

**Issue by charbs-io** [j-wil/pocket-nuxt#9]
Thanks for the project. Very useful.

I'm new to Nuxt 3, and assessing its server api capacity.

I'm trying to consume the `usePocketbase` composable in a server api route.

```
// /server/api/auth/login.post.ts
export default defineEventHandler(async (event) => {
  const pocketbase = usePocketbase();

  ...
});
```

I'm basically getting a 500 `usePocketbase` is not defined error. How can I make it so this can be used on the server api route?

Thanks!

**Comment by sifferhans** [comment]
@charbs-io You probably need to explicitly import the `usePocketbase` composable, as I don't think auto-imports works the same in the server directory.

```ts
// /server/api/auth/login.post.ts
import { usePocketbase } from '~/composables/pocketbase.ts' // or from '#imports'

export default defineEventHandler(async (event) => {
  const pocketbase = usePocketbase();
  ...
});
```

**Comment by j-wil** [comment]
@charbs-io was sifferhans able to answer your question?

If not I can dig in further
